"""Init

Revision ID: b7de8ab8833d
Revises: 
Create Date: 2024-03-13 17:51:56.861754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b7de8ab8833d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('iban', sa.String(length=34), nullable=False),
    sa.Column('bic', sa.String(length=11), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('balance', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.Enum('EUR', name='currency'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('iban')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('accounts')
    # ### end Alembic commands ###
